
language:
  - cpp
  
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty

    compiler:
      - gcc

    before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake
          - g++-4.9
          - qtbase5-dev
      coverity_scan:
        project:
          name: "igormironchik/args-parser"
          description: "Build submitted via Travis CI"
        notification_email: igor.mironchik@gmail.com
        build_command_prepend: echo 'Starting prebuild step...'; sudo ln -s -f /usr/bin/g++-4.9 /usr/bin/g++; sudo ln -s -f /usr/bin/gcc-4.9 /usr/bin/gcc; mkdir build; cd build; cmake ..; echo 'Prebuild step finished...';
        build_command: make
        branch_pattern: coverity_scan
    
    after_success:
      - cd ${TRAVIS_BUILD_DIR}
      - lcov --directory . --capture --output-file coverage.info coverage info
      - lcov --remove coverage.info '/usr/*' --output-file coverage.info
      - lcov --list coverage.info
      - bash <(curl -s https://codecov.io/bash)

    script:
      - |
        if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then \
          export CXX="g++-4.9" CC="gcc-4.9" || { exit 1; }; \
          mkdir build || { exit 1; }; \
          cd build || { exit 1; }; \
          cmake -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .. || { exit 1; }; \
          make || { exit 1; }; \
          ctest --output-on-failure || { exit 1; }; \
          fi
          
  - os: osx
    compiler: clang
    dist: xcode12u
    before_install:
      - brew install qt5
    env:
      - Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5
      
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make
      - ctest --output-on-failure
      
